apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: fullstack
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: ghcr.io/jonasbjork/fullstack:latest
      importPolicy:
        scheduled: true
