name: Test and build application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    
    - name: Run Flake8
      run: |
        flake8 src

    - name: Install dependencies
      run: |
        pip install -r src/requirements.txt
        pip install pytest

    - name: Run pytest
      run: |
        pytest -v

    - name: Build Docker image
      run: |
        docker build -t fullstack:latest .
  
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Tag the container image
      run: |
        docker tag fullstack:latest ghcr.io/${{ github.actor }}/fullstack:latest
        docker tag fullstack:latest ghcr.io/${{ github.actor }}/fullstack:${{ github.sha }}
    
    - name: Push the container image
      run: |
        docker push ghcr.io/${{ github.actor }}/fullstack:latest
        docker push ghcr.io/${{ github.actor }}/fullstack:${{ github.sha }}
    
    - name: Installera OpenShift CLI
      run: |
        curl -LO "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz"
        tar -xvf openshift-client-linux.tar.gz
        sudo mv oc kubectl /usr/local/bin/

    - name: OpenShift pull new image
      run: |
        oc login --token=${{ secrets.OCP_FULLSTACK_TOKEN }} --server=${{ secrets.OCP_FULLSTACK_SERVER }} --insecure-skip-tls-verify=true
        oc project test
        oc import-image fullstack:latest --confirm
